name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit:
    name: Debug ci
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Debug Info
        run: docker info
