name: PHPStan Tests

on:
  push:
    branches:
      - main
      - improve_ci
  pull_request:
    paths:
    - '.forgejo/workflows/phpstan-tests.yml'
    - 'includes/**'
    - 'phpstan.neon.dist'
    - 'composer.*'

env:
  WP_TESTS_DIR: /workspace/wordpress-test-lib
  WP_CORE_DIR: /workspace/wordpress

jobs:
  phpstan:
    runs-on: codeberg-medium
    strategy:
      matrix:
        php-version: ['8.4']
        wordpress-version: ['6.8']
        gatherpress-version: ['develop']
        activitypub-version: ['trunk']
    name: PHPStan – PHP ${{ matrix.php-version }}
    env:
      extensions: mysql, dom, iconv, json, libxml, zip
      GATHERPRESS_VERSION: ${{ matrix.gatherpress-version }}
      ACTIVITYPUB_VERSION: ${{ matrix.activitypub-version }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Cache WordPress Setup including the GatherPress and ActivityPub plugin
        id: cache-wordpress
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: |
            ${{ env.WP_CORE_DIR }}
            ${{ env.WP_TESTS_DIR }}
          key: ${{ matrix.wordpress-version }}-${{ matrix.gatherpress-version }}-${{ matrix.activitypub-version }}

      - name: Cache Composer
        id: cache-composer
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: ./vendor/
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Setup cache environment for PHP Extensions
        id: php-extensions-cache
        uses: https://github.com/shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          key: php-extensions-cache-1

      - name: Cache PHP extensions
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: ${{ steps.php-extensions-cache.outputs.dir }}
          key: ${{ steps.php-extensions-cache.outputs.key }}
          restore-keys: ${{ steps.php-extensions-cache.outputs.key }}

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@2.35.5
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          coverage: none
          tools: composer, cs2pr
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Install Composer dependencies for PHP
        if: steps.cache-composer.outputs.cache-hit != 'true'
        uses: https://github.com/ramsey/composer-install@v3
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}"}}'
          GITHUB_TOKEN: ${{ env.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Setup WordPress + GatherPress/ActivityPub files
        if: steps.cache-wordpress.outputs.cache-hit != 'true'
        run: bash .forgejo/scripts/install-wp-tests.sh wordpress_test root root mariadb ${{ matrix.wordpress-version }} true false
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}"}}'
          GITHUB_TOKEN: ${{ env.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Running PHPStan Analyze
        if: ${{ success() || failure() }}
        run: |
          ./vendor/bin/phpstan --version
          ./vendor/bin/phpstan  analyze -vv --memory-limit=2G --error-format=checkstyle | cs2pr
