name: PHPUnit Tests
on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - '.forgejo/workflows/phpunit-tests.yml'
    - 'includes/**'
    - 'test/unit/php**'
    - '*.php'
    - 'phpunit.xml.dist'
    - 'composer.*'
jobs:
  test-php:
    name: PHP ${{ matrix.php_versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_versions: [ '8.4' ]
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        run: 'printenv | grep DOCKER_HOST'

      - name: Cache Composer
        id: cache-composer-node
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: |
            ./vendor/
          key: cache-composer-1

      - name: Setup cache environment for PHP Extensions
        id: php-extensions-cache
        uses: https://github.com/shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, iconv, json, libxml, zip
          key: php-extensions-cache-1

      - name: Cache PHP extensions
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: ${{ steps.php-extensions-cache.outputs.dir }}
          key: ${{ steps.php-extensions-cache.outputs.key }}
          restore-keys: ${{ steps.php-extensions-cache.outputs.key }}

      - name: Cache NodeJS packages
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: |
            ./node_modules/
          key: cache-node-1

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, iconv, json, libxml, zip
          coverage: xdebug
          tools: composer, cs2pr
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Install composer dependencies
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: composer install --optimize-autoloader --prefer-dist
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}"}}'
          GITHUB_TOKEN: ${{ env.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          # Enable built-in functionality for caching and restoring dependencies, which is disabled by default.
          # The actions/setup-node uses actions/cache under the hood.
          # https://github.com/actions/setup-node#caching-global-packages-data
          cache: 'npm'

      - name: Install NodeJS dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: |
          npm i -g @wordpress/env
          npm install
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}"}}'
          GITHUB_TOKEN: ${{ env.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Log debug information
        run: |
          npm --version
          node --version
          git --version
          php --version
          composer --version
          printenv | grep DOCKER_HOST

      - name: Running PHPUnit Tests
        run: |
          php --version
          npm run test:unit:php
        if: ${{ success() || failure() }}