name: PHPUnit Tests

on:
  push:
    branches:
      - main
      - ci_wp_env
  pull_request:
    paths:
    - '.forgejo/workflows/phpunit-tests.yml'
    - 'includes/**'
    - 'test/unit/php**'
    - '*.php'
    - 'phpunit.xml.dist'
    - 'composer.*'

jobs:
  test-php:
    name: PHP ${{ matrix.php-version }}
    runs-on: docker
    steps:
      - name: Install packages
        run: |
          apk add --update npm bash sudo

      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Install NodeJS dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: |
          npm i -g @wordpress/env
          npm install
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}"}}'
          GITHUB_TOKEN: ${{ env.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Running PHPUnit Tests
        run: |
          docker info
          npm run test:unit:php
        if: ${{ success() || failure() }}
