name: PHPUnit Tests
on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - '.forgejo/workflows/phpunit-tests.yml'
    - 'includes/**'
    - 'test/unit/php**'
    - '*.php'
    - 'phpunit.xml.dist'
    - 'composer.*'
jobs:
  test-php:
    name: PHP ${{ matrix.php_versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_versions: [ '8.4' ]
    steps:
      - name: Test
        run: docker info
        env:
          DOCKER_HOST: tcp://docker-in-docker:2375
