name: PHPUnit Tests
on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - '.forgejo/workflows/phpunit-tests.yml'
    - 'includes/**'
    - 'test/unit/php**'
    - '*.php'
    - 'phpunit.xml.dist'
    - 'composer.*'
jobs:
  test-php:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v6
        with:
          submodules: true

      # - name: Setup PHP
      #   uses: https://github.com/shivammathur/setup-php@v2
      #   with:
      #     php-version: latest
      #     coverage: xdebug

      # - name: Install Composer dependencies
      #   uses: https://github.com/ramsey/composer-install@v3
      #   env:
      #     COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}"}}'
      #     GITHUB_TOKEN: ${{ env.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Cache NodeJS packages
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: |
            ./node_modules/
          key: cache-node-1

      - name: Install NodeJS
        uses: https://code.forgejo.org/actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          # Enable built-in functionality for caching and restoring dependencies, which is disabled by default.
          # The actions/setup-node uses actions/cache under the hood.
          # https://github.com/actions/setup-node#caching-global-packages-data

      - name: Install NodeJS dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: |
          npm i -g @wordpress/env
          npm install
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}"}}'
          GITHUB_TOKEN: ${{ env.ACCESS_TOKEN_FOR_GITHUB }}

      - name: Detect Host Path for /workspace and adjust mappings for .wp-env.json
        run: |
          CONTAINER_ID=$(basename $(cat /proc/1/cpuset))
          HOST_WORKSPACE_PATH=$(docker inspect $CONTAINER_ID | jq -r '.Mounts[] | select(.Destination=="/workspace") | .Source')

          if [[ -z "$HOST_WORKSPACE_PATH" ]]; then
            echo "Error: Unable to detect host workspace path." >&2
            exit 1
          fi

          echo "Detected host workspace path: $HOST_WORKSPACE_PATH"

          PLUGIN_PATH="${HOST_WORKSPACE_PATH}/Event-Federation/gatherpress-activitypub"

          # Path to .wp-env.json file
          WP_ENV_JSON="./.wp-env.json"

          # Verify .wp-env.json exists
          if [[ ! -f "$WP_ENV_JSON" ]]; then
            echo "Error: .wp-env.json not found!" >&2
            exit 1
          fi

          # Update the .wp-env.json file on the fly using jq
          jq --arg pluginPath "$PLUGIN_PATH" '
            .mappings["wp-content/plugins/gatherpress-activitypub"] = {
              "type": "local",
              "path": $pluginPath,
              "basename": "gatherpress-activitypub"
            }' "$WP_ENV_JSON" > "$WP_ENV_JSON.tmp" && mv "$WP_ENV_JSON.tmp" "$WP_ENV_JSON"

          # Print the updated file for debugging
          echo "Updated .wp-env.json:"
          cat "$WP_ENV_JSON"

      - name: Start WordPress Environment
        run: |
          echo "Starting WordPress environment with updated mappings..."
          npx wp-env start

      - name: Running PHPUnit Tests
        run: |
          wp-env start --debug
          wp-env run cli ls -l
          wp-env run cli ls -l ./wp-content/plugins
          wp-env run cli echo $PWD
          wp-env run cli ls -l ./wp-content/plugins/gatherpress-activitypub
          wp-env run cli ls -l ./wp-content/plugins/gatherpress-activitypub2
          cat /proc/mounts
        if: ${{ success() || failure() }}
