name: PHPUnit Tests
on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - '.forgejo/workflows/phpunit-tests.yml'
    - 'includes/**'
    - 'test/unit/php**'
    - '*.php'
    - 'phpunit.xml.dist'
    - 'composer.*'
jobs:
  test-php:
    name: PHP ${{ matrix.php_versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_versions: [ '8.4' ]
    steps:
      - name: Test hosts file
        run: cat /etc/hosts
      - name: Test reach dind
        run: curl http://dind_container:2375/info 
      - name: Test docker info
        run: docker info
